// Generated by CoffeeScript 1.3.1
(function() {
  var commented_lines, q, test;

  window.doctest = function(url) {
    var $script;
    if (/^[.]/.test(url) && ($script = jQuery('script[src$="doctest.js"]')).length) {
      url = $script.attr('src').replace(/doctest[.]js$/, url);
    }
    console.log("retrieving " + url + "...");
    return jQuery.get(url, function(text) {
      var actual, expected, num, pass, r, results, _i, _len, _ref, _ref1, _results;
      results = test(text);
      console.log("running doctests in " + url + "...");
      console.log(((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          pass = results[_i].pass;
          _results.push(pass ? '.' : 'x');
        }
        return _results;
      })()).join(''));
      _ref = (function() {
        var _j, _len, _results1;
        _results1 = [];
        for (_j = 0, _len = results.length; _j < _len; _j++) {
          r = results[_j];
          if (!r.pass) {
            _results1.push(r);
          }
        }
        return _results1;
      })();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], pass = _ref1.pass, expected = _ref1.expected, actual = _ref1.actual, num = _ref1.num;
        _results.push(console.warn("expected " + (q(expected)) + " on line " + num + " (got " + (q(actual)) + ")"));
      }
      return _results;
    });
  };

  window.doctest.version = '0.1.0';

  commented_lines = function(text) {
    var idx, line, lines, match, _i, _len, _ref;
    lines = [];
    _ref = text.split(/\r?\n|\r/);
    for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
      line = _ref[idx];
      if (match = /^[ \t]*\/\/[ \t]*(.+)/.exec(line)) {
        lines.push([idx + 1, match[1]]);
      }
    }
    return lines;
  };

  test = function(text) {
    var actual, expected, expr, line, match, num, results, _i, _len, _ref, _ref1;
    results = [];
    expr = '';
    _ref = commented_lines(text);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      _ref1 = _ref[_i], num = _ref1[0], line = _ref1[1];
      if (match = /^>(.*)/.exec(line)) {
        eval(expr);
        expr = match[1];
      } else if (match = /^[.](.*)/.exec(line)) {
        expr += '\n' + match[1];
      } else if (expr) {
        actual = eval(expr);
        expected = eval(line);
        results.push({
          actual: actual,
          expected: expected,
          num: num,
          pass: _.isEqual(expected, actual)
        });
        expr = '';
      }
    }
    return results;
  };

  q = function(object) {
    if (typeof object === 'string') {
      return "\"" + object + "\"";
    } else {
      return object;
    }
  };

}).call(this);
