// Generated by CoffeeScript 1.4.0
(function() {
  var argv, optimist, usage;

  optimist = require('optimist');

  usage = '\nUsage: doctest file [file ...]\n\n`file` must be a JavaScript or CoffeeScript file with the appropriate\nextension.';

  argv = optimist.usage(usage).options({
    h: {
      alias: 'help'
    }
  }).argv;

  if (argv.help || argv._.length === 0) {
    optimist.showHelp();
  } else {
    require('../lib/doctest').apply(null, argv._);
  }

}).call(this);
