// Generated by CoffeeScript 1.4.0
(function() {
  var argv, doctest, optimist, usage;

  optimist = require('optimist');

  usage = '\nUsage: doctest file [file ...]\n\n`file` must be a JavaScript or CoffeeScript file with the appropriate\nextension.';

  argv = optimist.usage(usage).options({
    h: {
      alias: 'help'
    },
    d: {
      alias: 'dump'
    }
  }).argv;

  if (argv.help || argv._.length === 0) {
    optimist.showHelp();
  } else {
    doctest = require('../lib/doctest');
    if (argv.dump) {
      doctest.dump = true;
    }
    doctest.apply(null, argv._);
  }

}).call(this);
