#!/usr/bin/env bash
set -euf -o pipefail

source "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")/node_modules/sanctuary-scripts/functions"

branches="$(get min-branch-coverage)"

set +f ; shopt -s globstar nullglob
# shellcheck disable=SC2207
source_files=($(get source-files))
# shellcheck disable=SC2207
test_files=($(get test-files))
set -f ; shopt -u globstar nullglob

args=(
  --check-coverage
  --branches    "$branches"
  --functions   0
  --lines       0
  --statements  0
)
for name in "${source_files[@]}" ; do
  args+=(--include "$name")
done
node_modules/.bin/c8 "${args[@]}" -- node --experimental-vm-modules -- node_modules/.bin/oletus -- "${test_files[@]}"
