name: test
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npx doctest --module commonjs **/*.js
      # - run: |
      #     npm install doctest --save-dev
      #     npm install standard --save-dev
      #     npx doctest **/*.js
      #     npx standard
      #     npm ci
      #     npm run build --if-present
      #     npm test
